steps:

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin

- task: MicroBuildSwixPlugin@1
  displayName: Install MicroBuild Swix Plugin
