steps:
- task: MicroBuildCleanup@1
  condition: succeededOrFailed()
  displayName: MicroBuild Cleanup

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: Component Detection
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetCommand@2
  inputs:
    command: push
    searchPatternPush: '$(Build.SourcesDirectory)\bin\**\$(BuildConfiguration)\**\*.nupkg;!**\*.symbols.nupkg;!**/VS.*.nupkg'
    publishVstsFeed: $(feedGuid)
    allowPackageConflicts: true
  displayName: Push packages to VSTS feed
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

# The Convert-PDB.ps1 script uses nuget.exe at the cmdline, so make sure it's on our PATH
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 5.4.0
  displayName: Pin nuget.exe version

- powershell: |
    $DllPaths = @(
        ,"src\libman.dll"
        ,"src\Microsoft.Web.LibraryManager.dll"
        ,"src\Microsoft.Web.LibraryManager.Build.dll"
        ,"src\Microsoft.Web.LibraryManager.Contracts.dll"
        ,"src\Microsoft.Web.LibraryManager.Vsix.dll"
    )
    Get-ChildItem $DllPaths -rec |? { !$_.Directory.FullName.Contains('Tests') } |% {
        $OutputDir = "$($_.Directory.FullName)\symstore"
        if (!(Test-Path $OutputDir)) { mkdir $OutputDir | Out-Null }
        Write-Host "Converting PDB for $_"
        azure-pipelines\Convert-PDB.ps1 -DllPath $_ -OutputPath "$OutputDir\$($_.BaseName).pdb"
    }
  displayName: Converting portable PDBs to Windows PDBs

- task: CopyFiles@1
  inputs:
    SourceFolder: src
    Contents: |
      libman/bin/$(BuildConfiguration)/**/libman.dll
      libman/bin/$(BuildConfiguration)/**/symstore/libman.pdb
      LibraryManager/bin/$(BuildConfiguration)/**/Microsoft.Web.LibraryManager.dll
      LibraryManager/bin/$(BuildConfiguration)/**/symstore/Microsoft.Web.LibraryManager.pdb
      LibraryManager.Build/bin/$(BuildConfiguration)/**/Microsoft.Web.LibraryManager.Build.dll
      LibraryManager.Build/bin/$(BuildConfiguration)/**/symstore/Microsoft.Web.LibraryManager.Build.pdb
      LibraryManager.Contracts/bin/$(BuildConfiguration)/**/Microsoft.Web.LibraryManager.Contracts.dll
      LibraryManager.Contracts/bin/$(BuildConfiguration)/**/symstore/Microsoft.Web.LibraryManager.Contracts.pdb
      LibraryManager.Vsix/bin/$(BuildConfiguration)/**/Microsoft.Web.LibraryManager.Vsix.dll
      LibraryManager.Vsix/bin/$(BuildConfiguration)/**/symstore/Microsoft.Web.LibraryManager.Vsix.pdb
    TargetFolder: $(Build.ArtifactStagingDirectory)/symbols
  displayName: Collecting symbols artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/symbols
    ArtifactName: symbols
    ArtifactType: Container
  displayName: Publish symbols as Azure DevOps artifacts

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Build.ArtifactStagingDirectory)/symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish symbols to symbol server
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
